export const categories = [
    "Introduction to AI and Its Applications",
"AI benefits and Drawbacks",
"History of AI",
"AI in business intelligence",
"AI in healthcare",
"AI in education",
"AI in manufacturing",
"AI in Navigation",
"Natural Language Processing",
"Computer Vision",
"Face Recognition",
"AI applications in Agriculture",
"AI application is gaming",
"AI in automotive industry",
"AI in social media platforms",
"AI in marketing",
"AI-powered chatbots",
"AI in the banking and finance industry ",
"AI applications is astronomy",
"AI for Data Security",
"AI for Travel and Transport",
"Generative AI",
"AI in entertainment industry",
"Is Artificial Intelligence Limiting Human Application?",
"How is AI likely to be used in the future?",
"Can AI replace human intelligence?",
"AI Arms Race",
"Impact of AI in employment",
"INTELLIGENT AGENTS",
"AGENT FUNCTION & AGENT PROGRAM",
"Task Environment",
"Environment types",
"kinds of agent programs",
"Problem-Solving Agent",
"Toy Problems: 8-Puzzle",
"Toy Problems: 8-Queens",
"Route-finding problems",
"Touring problems",
"Traveling Salesman problem",
"VLSI layout problem",
"Robot navigation",
"Automatic assembly sequencing",
"Internet searching",
"Tree Search",
"Breadth-First Search",
"Uniform-cost search",
"Depth-first search",
"Greedy Best Fit Seach ",
"A* search",
]