export const categories = [
    "Introduction to AI and Its Applications",
    "AI Benefits and Drawbacks",
    "History of AI",
    "AI in Business Intelligence",
    "AI in Healthcare",
    "AI in Education",
    "AI in Manufacturing",
    "AI in Navigation",
    "Natural Language Processing",
    "Computer Vision",
    "Face Recognition",
    "AI Applications in Agriculture",
    "AI Applications in Gaming",
    "AI in the Automotive Industry",
    "AI in Social Media Platforms",
    "AI in Marketing",
    "AI-powered Chatbots",
    "AI in the Banking and Finance Industry",
    "AI Applications in Astronomy",
    "AI for Data Security",
    "AI for Travel and Transport",
    "Generative AI",
    "AI in the Entertainment Industry",
    "Is Artificial Intelligence Limiting Human Application?",
    "How is AI Likely to Be Used in the Future?",
    "Can AI Replace Human Intelligence?",
    "AI Arms Race",
    "Impact of AI on Employment",
    "Intelligent Agents",
    "Agent Function & Agent Program",
    "Task Environment",
    "Environment Types",
    "Kinds of Agent Programs",
    "Problem-Solving Agent",
    "Toy Problems: 8-Puzzle",
    "Toy Problems: 8-Queens",
    "Route-Finding Problems",
    "Touring Problems",
    "Traveling Salesman Problem",
    "VLSI Layout Problem",
    "Robot Navigation",
    "Automatic Assembly Sequencing",
    "Internet Searching",
    "Tree Search",
    "Breadth-First Search",
    "Uniform-Cost Search",
    "Depth-First Search",
    "Greedy Best-First Search",
    "A* Search"
  ];
  